Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50
AllCops:
  EnabledByDefault: true

Lint/ConstantResolution:
  Enabled: false
